import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowRight,
  Award,
  BarChart3,
  BookOpenText,
  Bot,
  BriefcaseBusiness,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Dumbbell,
  Euro,
  Eye,
  EyeOff,
  FileText,
  Flame,
  GraduationCap,
  HeartPulse,
  HelpCircle,
  Home,
  Info,
  Landmark,
  LayoutGrid,
  Lightbulb,
  Link2,
  Loader2,
  LogIn,
  Mail,
  MapPin,
  MoreHorizontal,
  MoreVertical,
  NotebookPen,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  Pin,
  PlugZap,
  Plus,
  Power,
  Radar,
  RefreshCw,
  Router,
  Save,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  StickyNote,
  Sunrise,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  Wallet,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const APP_ICONS = {
  activity: Activity,
  add: Plus,
  agenda: CalendarClock,
  alert: AlertCircle,
  archive: Archive,
  arrowRight: ArrowRight,
  award: Award,
  automations: Zap,
  backlinks: Link2,
  bot: Bot,
  book: BookOpenText,
  business: BriefcaseBusiness,
  calendar: Calendar,
  calendarDays: CalendarDays,
  categoryAdmin: ClipboardList,
  categoryHealth: HeartPulse,
  categoryMaintenance: Wrench,
  categoryOther: Pin,
  categorySocial: Coffee,
  categorySport: Dumbbell,
  categoryStudy: GraduationCap,
  categoryWork: BriefcaseBusiness,
  categoryEvent: PartyPopper,
  chart: BarChart3,
  check: Check,
  close: X,
  cloud: Cloud,
  collapse: ChevronDown,
  dashboard: Home,
  delete: Trash2,
  edit: Pencil,
  file: FileText,
  finance: Landmark,
  flame: Flame,
  habit: Target,
  help: HelpCircle,
  hide: EyeOff,
  home: Home,
  info: Info,
  light: Lightbulb,
  lights: Lightbulb,
  list: LayoutGrid,
  loading: Loader2,
  location: MapPin,
  login: LogIn,
  mail: Mail,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  next: ChevronRight,
  note: StickyNote,
  notes: StickyNote,
  pageNote: NotebookPen,
  palette: Palette,
  pause: Pause,
  pin: Pin,
  plug: PlugZap,
  power: Power,
  previous: ChevronLeft,
  radar: Radar,
  refresh: RefreshCw,
  roster: Calendar,
  router: Router,
  save: Save,
  schedule: CalendarCheck,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  statusActive: Circle,
  statusOk: CheckCircle2,
  tag: Tag,
  time: Clock,
  timer: Timer,
  money: Euro,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  trophy: Trophy,
  upload: Upload,
  wallet: Wallet,
  warning: AlertTriangle,
  wifi: Wifi,
  wifiOff: WifiOff,
  work: BriefcaseBusiness,
  show: Eye,
  sunrise: Sunrise,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;

export const EVENT_CATEGORY_SYMBOLS = [
  { id: "sociaal", icon: "categorySocial", label: "Sociaal" },
  { id: "werk", icon: "categoryWork", label: "Werk" },
  { id: "gezondheid", icon: "categoryHealth", label: "Gezondheid" },
  { id: "sport", icon: "categorySport", label: "Sport" },
  { id: "admin", icon: "categoryAdmin", label: "Admin" },
  { id: "studie", icon: "categoryStudy", label: "Studie" },
  { id: "onderhoud", icon: "categoryMaintenance", label: "Onderhoud" },
  { id: "evenement", icon: "categoryEvent", label: "Evenement" },
  { id: "overig", icon: "categoryOther", label: "Overig" },
] as const satisfies ReadonlyArray<{ id: string; icon: AppIconName; label: string }>;
