import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowRight,
  Award,
  BarChart3,
  BookOpenText,
  Bot,
  BriefcaseBusiness,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Dumbbell,
  Euro,
  Eye,
  EyeOff,
  FileText,
  Flame,
  GraduationCap,
  HeartPulse,
  HelpCircle,
  Home,
  Info,
  Landmark,
  LayoutGrid,
  Lightbulb,
  Link2,
  Loader2,
  LogIn,
  Mail,
  MapPin,
  MoreHorizontal,
  MoreVertical,
  NotebookPen,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  Pin,
  PlugZap,
  Plus,
  Power,
  Radar,
  RefreshCw,
  Router,
  Save,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  StickyNote,
  Sunrise,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  Wallet,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const APP_ICONS = {
  activity: Activity,
  add: Plus,
  agenda: CalendarClock,
  alert: AlertCircle,
  archive: Archive,
  arrowRight: ArrowRight,
  award: Award,
  automations: Zap,
  backlinks: Link2,
  bot: Bot,
  book: BookOpenText,
  business: BriefcaseBusiness,
  calendar: Calendar,
  calendarDays: CalendarDays,
  categoryAdmin: ClipboardList,
  categoryHealth: HeartPulse,
  categoryMaintenance: Wrench,
  categoryOther: Pin,
  categorySocial: Coffee,
  categorySport: Dumbbell,
  categoryStudy: GraduationCap,
  categoryWork: BriefcaseBusiness,
  categoryEvent: PartyPopper,
  chart: BarChart3,
  check: Check,
  close: X,
  cloud: Cloud,
  collapse: ChevronDown,
  dashboard: Home,
  delete: Trash2,
  edit: Pencil,
  file: FileText,
  finance: Landmark,
  flame: Flame,
  habit: Target,
  help: HelpCircle,
  hide: EyeOff,
  home: Home,
  info: Info,
  light: Lightbulb,
  lights: Lightbulb,
  list: LayoutGrid,
  loading: Loader2,
  location: MapPin,
  login: LogIn,
  mail: Mail,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  next: ChevronRight,
  note: StickyNote,
  notes: StickyNote,
  pageNote: NotebookPen,
  palette: Palette,
  pause: Pause,
  pin: Pin,
  plug: PlugZap,
  power: Power,
  previous: ChevronLeft,
  radar: Radar,
  refresh: RefreshCw,
  roster: Calendar,
  router: Router,
  save: Save,
  schedule: CalendarCheck,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  statusActive: Circle,
  statusOk: CheckCircle2,
  tag: Tag,
  time: Clock,
  timer: Timer,
  money: Euro,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  trophy: Trophy,
  upload: Upload,
  wallet: Wallet,
  warning: AlertTriangle,
  wifi: Wifi,
  wifiOff: WifiOff,
  work: BriefcaseBusiness,
  show: Eye,
  sunrise: Sunrise,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;

export type SymbolOption = {
  id: string;
  icon: AppIconName;
  label: string;
};

export const EVENT_CATEGORY_SYMBOLS = [
  { id: "sociaal", icon: "categorySocial", label: "Sociaal" },
  { id: "werk", icon: "categoryWork", label: "Werk" },
  { id: "gezondheid", icon: "categoryHealth", label: "Gezondheid" },
  { id: "sport", icon: "categorySport", label: "Sport" },
  { id: "admin", icon: "categoryAdmin", label: "Admin" },
  { id: "studie", icon: "categoryStudy", label: "Studie" },
  { id: "onderhoud", icon: "categoryMaintenance", label: "Onderhoud" },
  { id: "evenement", icon: "categoryEvent", label: "Evenement" },
  { id: "overig", icon: "categoryOther", label: "Overig" },
] as const satisfies ReadonlyArray<SymbolOption>;

export const NOTE_SYMBOL_OPTIONS = [
  { id: "note", icon: "note", label: "Notitie" },
  { id: "laventecare", icon: "business", label: "LaventeCare" },
  { id: "pageNote", icon: "pageNote", label: "Pagina" },
  { id: "book", icon: "book", label: "Logboek" },
  { id: "list", icon: "list", label: "Lijst" },
  { id: "check", icon: "check", label: "Actie" },
  { id: "pin", icon: "pin", label: "Belangrijk" },
  { id: "calendar", icon: "calendar", label: "Datum" },
  { id: "time", icon: "time", label: "Tijd" },
  { id: "warning", icon: "warning", label: "Urgent" },
  { id: "work", icon: "work", label: "Werk" },
  { id: "finance", icon: "finance", label: "Financie" },
  { id: "habit", icon: "habit", label: "Habit" },
  { id: "shield", icon: "shield", label: "Prive" },
  { id: "sparkles", icon: "sparkles", label: "Idee" },
  { id: "light", icon: "light", label: "Inzicht" },
] as const satisfies ReadonlyArray<SymbolOption>;

export const EVENT_SYMBOL_OPTIONS = [
  { id: "agenda", icon: "agenda", label: "Afspraak" },
  { id: "laventecare", icon: "business", label: "LaventeCare" },
  { id: "calendar", icon: "calendar", label: "Kalender" },
  { id: "time", icon: "time", label: "Tijd" },
  { id: "location", icon: "location", label: "Locatie" },
  ...EVENT_CATEGORY_SYMBOLS,
] as const satisfies ReadonlyArray<SymbolOption>;

export function isAppIconName(value?: string | null): value is AppIconName {
  return Boolean(value && Object.prototype.hasOwnProperty.call(APP_ICONS, value));
}

export function resolveAppIconName(value?: string | null, fallback: AppIconName = "note"): AppIconName {
  return isAppIconName(value) ? value : fallback;
}

export function getEventCategoryIcon(categoryId?: string | null): AppIconName {
  return EVENT_CATEGORY_SYMBOLS.find((category) => category.id === categoryId)?.icon ?? "categoryOther";
}
