/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export type GetEmailsParams = {
/**
 * User ID
 */
user_id: string;
/**
 * Limit count
 */
limit?: number;
/**
 * Offset count
 */
offset?: number;
/**
 * Category filter
 */
categorie?: string;
};
