/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export type GetHabitsHeatmapParams = {
/**
 * User ID
 */
userId: string;
/**
 * Number of days
 */
days?: number;
};
