/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCActionItem {
  action_type?: string;
  created_at?: string;
  due_date?: string;
  id?: string;
  linked_lead_id?: string;
  linked_project_id?: string;
  priority?: string;
  source?: string;
  source_id?: string;
  status?: string;
  summary?: string;
  title?: string;
  updated_at?: string;
  user_id?: string;
}
