/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalModelSceneActionCreate } from './githubComJeffreasyJeffriesBackendInternalModelSceneActionCreate';

export interface GithubComJeffreasyJeffriesBackendInternalModelSceneCreate {
  actions?: GithubComJeffreasyJeffriesBackendInternalModelSceneActionCreate[];
  color_hex?: string;
  icon?: string;
  name?: string;
}
