/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCBusinessSignal {
  action_hint?: string;
  date?: string;
  id?: string;
  matched_term?: string;
  source?: string;
  subtitle?: string;
  title?: string;
  urgency?: string;
}
