/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelPrivacySettings {
  account?: boolean;
  email?: boolean;
  finance?: boolean;
  habits?: boolean;
  id?: string;
  notes?: boolean;
  updated_at?: string;
  user_id?: string;
}
