/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCCockpitSummary {
  actionItems?: number;
  activeLeads?: number;
  activeProjects?: number;
  businessSignals?: number;
  decisions?: number;
  documents?: number;
  documentsSeeded?: boolean;
  followUps?: number;
  leads?: number;
  openChanges?: number;
  openIncidents?: number;
  projects?: number;
}
