/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalModelLoonstrookComponenten } from './githubComJeffreasyJeffriesBackendInternalModelLoonstrookComponenten';
import type { GithubComJeffreasyJeffriesBackendInternalModelLoonstrookCumulatieven } from './githubComJeffreasyJeffriesBackendInternalModelLoonstrookCumulatieven';
import type { GithubComJeffreasyJeffriesBackendInternalModelLoonstrookOrtDetail } from './githubComJeffreasyJeffriesBackendInternalModelLoonstrookOrtDetail';

export interface GithubComJeffreasyJeffriesBackendInternalModelLoonstrook {
  amt_zeerintensief?: number;
  bruto_betaling?: number;
  bruto_inhouding?: number;
  componenten?: GithubComJeffreasyJeffriesBackendInternalModelLoonstrookComponenten;
  cumulatieven?: GithubComJeffreasyJeffriesBackendInternalModelLoonstrookCumulatieven;
  eju_bedrag?: number;
  extra_uren_bedrag?: number;
  geimporteerd_op?: string;
  id?: string;
  jaar?: number;
  loonheffing?: number;
  netto?: number;
  ort_detail?: GithubComJeffreasyJeffriesBackendInternalModelLoonstrookOrtDetail;
  ort_totaal?: number;
  parttime_factor?: number;
  pensioenpremie?: number;
  periode?: number;
  periode_label?: string;
  reiskosten?: number;
  salaris_basis?: number;
  schaalnummer?: string;
  toeslag_balansvlf?: number;
  trede?: string;
  type?: string;
  user_id?: string;
  uurloon?: number;
  vakantietoeslag?: number;
}
