/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelDeviceRegisterRequest {
  ip_address?: string;
  name?: string;
  room_id?: string;
}
