/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelPersonalEvent {
  beschrijving?: string;
  conflict_met_dienst?: string;
  eind_datum?: string;
  eind_tijd?: string;
  event_id?: string;
  heledag?: boolean;
  id?: string;
  kalender?: string;
  locatie?: string;
  start_datum?: string;
  start_tijd?: string;
  status?: string;
  titel?: string;
  user_id?: string;
}
