/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCProject {
  company_id?: string;
  created_at?: string;
  deadline?: string;
  fase?: string;
  id?: string;
  lead_id?: string;
  naam?: string;
  samenvatting?: string;
  start_datum?: string;
  status?: string;
  updated_at?: string;
  user_id?: string;
  waarde_indicatie?: number;
}
