/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCDocument {
  categorie?: string;
  created_at?: string;
  document_key?: string;
  fase?: string;
  id?: string;
  samenvatting?: string;
  source_path?: string;
  tags?: string[];
  titel?: string;
  updated_at?: string;
  user_id?: string;
  versie?: string;
}
