/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalModelLCActionItem } from './githubComJeffreasyJeffriesBackendInternalModelLCActionItem';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCBusinessSignal } from './githubComJeffreasyJeffriesBackendInternalModelLCBusinessSignal';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCChangeRequest } from './githubComJeffreasyJeffriesBackendInternalModelLCChangeRequest';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCCockpitSummary } from './githubComJeffreasyJeffriesBackendInternalModelLCCockpitSummary';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCDecision } from './githubComJeffreasyJeffriesBackendInternalModelLCDecision';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCDocument } from './githubComJeffreasyJeffriesBackendInternalModelLCDocument';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCFollowUpSignal } from './githubComJeffreasyJeffriesBackendInternalModelLCFollowUpSignal';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCLead } from './githubComJeffreasyJeffriesBackendInternalModelLCLead';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCProject } from './githubComJeffreasyJeffriesBackendInternalModelLCProject';
import type { GithubComJeffreasyJeffriesBackendInternalModelLCSlaIncident } from './githubComJeffreasyJeffriesBackendInternalModelLCSlaIncident';

export interface GithubComJeffreasyJeffriesBackendInternalModelLCCockpit {
  actionItems?: GithubComJeffreasyJeffriesBackendInternalModelLCActionItem[];
  activeLeads?: GithubComJeffreasyJeffriesBackendInternalModelLCLead[];
  activeProjects?: GithubComJeffreasyJeffriesBackendInternalModelLCProject[];
  businessSignals?: GithubComJeffreasyJeffriesBackendInternalModelLCBusinessSignal[];
  documentCatalog?: GithubComJeffreasyJeffriesBackendInternalModelLCDocument[];
  followUps?: GithubComJeffreasyJeffriesBackendInternalModelLCFollowUpSignal[];
  openChanges?: GithubComJeffreasyJeffriesBackendInternalModelLCChangeRequest[];
  openIncidents?: GithubComJeffreasyJeffriesBackendInternalModelLCSlaIncident[];
  recentDecisions?: GithubComJeffreasyJeffriesBackendInternalModelLCDecision[];
  summary?: GithubComJeffreasyJeffriesBackendInternalModelLCCockpitSummary;
}
