/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCLead {
  bron?: string;
  company_id?: string;
  contact_id?: string;
  created_at?: string;
  fit_score?: number;
  id?: string;
  pijnpunt?: string;
  prioriteit?: string;
  source_id?: string;
  status?: string;
  titel?: string;
  updated_at?: string;
  user_id?: string;
  volgende_actie_datum?: string;
  volgende_stap?: string;
}
