/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalModelSceneActionTargetState } from './githubComJeffreasyJeffriesBackendInternalModelSceneActionTargetState';

export interface GithubComJeffreasyJeffriesBackendInternalModelSceneAction {
  device_id?: string;
  execution_order?: number;
  id?: string;
  scene_id?: string;
  target_state?: GithubComJeffreasyJeffriesBackendInternalModelSceneActionTargetState;
  transition_ms?: number;
}
