/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCFollowUpSignal {
  action_hint?: string;
  date?: string;
  id?: string;
  priority?: string;
  source?: string;
  status?: string;
  title?: string;
}
