/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalModelAutomationRowActionConfig } from './githubComJeffreasyJeffriesBackendInternalModelAutomationRowActionConfig';
import type { GithubComJeffreasyJeffriesBackendInternalModelAutomationRowTriggerConfig } from './githubComJeffreasyJeffriesBackendInternalModelAutomationRowTriggerConfig';

export interface GithubComJeffreasyJeffriesBackendInternalModelAutomationRow {
  action_config?: GithubComJeffreasyJeffriesBackendInternalModelAutomationRowActionConfig;
  created_at?: string;
  enabled?: boolean;
  group_name?: string;
  id?: string;
  last_fired_at?: string;
  name?: string;
  trigger_config?: GithubComJeffreasyJeffriesBackendInternalModelAutomationRowTriggerConfig;
  user_id?: string;
}
