/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelDeviceCommandRequest {
  b?: number;
  brightness?: number;
  color_temp_mireds?: number;
  g?: number;
  hue?: number;
  on?: boolean;
  r?: number;
  saturation?: number;
  scene_id?: number;
}
