/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalModelSceneAction } from './githubComJeffreasyJeffriesBackendInternalModelSceneAction';

export interface GithubComJeffreasyJeffriesBackendInternalModelScene {
  actions?: GithubComJeffreasyJeffriesBackendInternalModelSceneAction[];
  color_hex?: string;
  created_at?: string;
  icon?: string;
  id?: string;
  name?: string;
}
