/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { GithubComJeffreasyJeffriesBackendInternalStoreCategorieBreakdown } from './githubComJeffreasyJeffriesBackendInternalStoreCategorieBreakdown';
import type { GithubComJeffreasyJeffriesBackendInternalStoreMaandInUit } from './githubComJeffreasyJeffriesBackendInternalStoreMaandInUit';
import type { GithubComJeffreasyJeffriesBackendInternalStoreMaandSaldo } from './githubComJeffreasyJeffriesBackendInternalStoreMaandSaldo';
import type { GithubComJeffreasyJeffriesBackendInternalStoreTopMerchant } from './githubComJeffreasyJeffriesBackendInternalStoreTopMerchant';
import type { GithubComJeffreasyJeffriesBackendInternalStoreTransactionStatsHuidigSaldoPerIban } from './githubComJeffreasyJeffriesBackendInternalStoreTransactionStatsHuidigSaldoPerIban';
import type { GithubComJeffreasyJeffriesBackendInternalStoreTransactionStatsSaldoPeildatumPerIban } from './githubComJeffreasyJeffriesBackendInternalStoreTransactionStatsSaldoPeildatumPerIban';

export interface GithubComJeffreasyJeffriesBackendInternalStoreTransactionStats {
  aantalAlleTxs?: number;
  aantalCategorieen?: number;
  aantalTxs?: number;
  gemiddeldIn?: number;
  gemiddeldUit?: number;
  /** Echte bankbalans */
  huidigSaldo?: number;
  huidigSaldoPerIban?: GithubComJeffreasyJeffriesBackendInternalStoreTransactionStatsHuidigSaldoPerIban;
  ibannen?: string[];
  inPerCategorie?: GithubComJeffreasyJeffriesBackendInternalStoreCategorieBreakdown[];
  inUitPerMaand?: GithubComJeffreasyJeffriesBackendInternalStoreMaandInUit[];
  jaren?: string[];
  laatsteSaldoPeildatum?: string;
  maanden?: string[];
  nettoStroom?: number;
  saldoPeildatumPerIban?: GithubComJeffreasyJeffriesBackendInternalStoreTransactionStatsSaldoPeildatumPerIban;
  /** Grafieken */
  saldoPerMaand?: GithubComJeffreasyJeffriesBackendInternalStoreMaandSaldo[];
  /** Overige */
  storneringen?: number;
  topMerchants?: GithubComJeffreasyJeffriesBackendInternalStoreTopMerchant[];
  /** Kasstromen */
  totaalIn?: number;
  totaalUit?: number;
  /** Categorieën */
  uitPerCategorie?: GithubComJeffreasyJeffriesBackendInternalStoreCategorieBreakdown[];
}
