/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCLeadCreate {
  bron?: string;
  company_name?: string;
  fit_score?: number;
  pijnpunt?: string;
  prioriteit?: string;
  source_id?: string;
  titel?: string;
  volgende_actie_datum?: string;
  volgende_stap?: string;
  website?: string;
}
