/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface GithubComJeffreasyJeffriesBackendInternalModelLCSlaIncident {
  created_at?: string;
  gemeld_op?: string;
  id?: string;
  kanaal?: string;
  prioriteit?: string;
  project_id?: string;
  reactie_deadline?: string;
  samenvatting?: string;
  status?: string;
  titel?: string;
  updated_at?: string;
  user_id?: string;
}
