/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelTransaction } from './modelTransaction';

export interface HandlerTransactionListResponse {
  isDone?: boolean;
  page?: ModelTransaction[];
  totalCount?: number;
}
