/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelSceneActionCreateTargetState } from './modelSceneActionCreateTargetState';

export interface ModelSceneActionCreate {
  device_id?: string;
  execution_order?: number;
  target_state?: ModelSceneActionCreateTargetState;
  transition_ms?: number;
}
