/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelRoom {
  created_at?: string;
  floor_number?: number;
  icon?: string;
  id?: string;
  name?: string;
}
