/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelLCChangeRequest {
  budget_impact?: string;
  created_at?: string;
  id?: string;
  impact?: string;
  planning_impact?: string;
  project_id?: string;
  status?: string;
  titel?: string;
  updated_at?: string;
  user_id?: string;
}
