/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelLCConvertLeadToProject {
  fase?: string;
  lead_id?: string;
  naam?: string;
  samenvatting?: string;
  status?: string;
}
