/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelLCActionItem } from './modelLCActionItem';
import type { ModelLCBusinessSignal } from './modelLCBusinessSignal';
import type { ModelLCChangeRequest } from './modelLCChangeRequest';
import type { ModelLCCockpitSummary } from './modelLCCockpitSummary';
import type { ModelLCDecision } from './modelLCDecision';
import type { ModelLCDocument } from './modelLCDocument';
import type { ModelLCFollowUpSignal } from './modelLCFollowUpSignal';
import type { ModelLCLead } from './modelLCLead';
import type { ModelLCProject } from './modelLCProject';
import type { ModelLCSlaIncident } from './modelLCSlaIncident';

export interface ModelLCCockpit {
  actionItems?: ModelLCActionItem[];
  activeLeads?: ModelLCLead[];
  activeProjects?: ModelLCProject[];
  businessSignals?: ModelLCBusinessSignal[];
  documentCatalog?: ModelLCDocument[];
  followUps?: ModelLCFollowUpSignal[];
  openChanges?: ModelLCChangeRequest[];
  openIncidents?: ModelLCSlaIncident[];
  recentDecisions?: ModelLCDecision[];
  summary?: ModelLCCockpitSummary;
}
