/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelDeviceRegisterRequestCurrentState } from './modelDeviceRegisterRequestCurrentState';

export interface ModelDeviceRegisterRequest {
  current_state?: ModelDeviceRegisterRequestCurrentState;
  ip_address?: string;
  name?: string;
  room_id?: string;
  skip_probe?: boolean;
  status?: string;
}
