/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelLCLeadUpdate {
  fit_score?: number;
  pijnpunt?: string;
  prioriteit?: string;
  status?: string;
  volgende_actie_datum?: string;
  volgende_stap?: string;
}
