/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelEmail {
  bcc?: string;
  bijlagen_count?: number;
  categorie?: string;
  cc?: string;
  created_at?: string;
  datum?: string;
  from_addr?: string;
  gmail_id?: string;
  heeft_bijlagen?: boolean;
  id?: string;
  is_draft?: boolean;
  is_gelezen?: boolean;
  is_ster?: boolean;
  is_verwijderd?: boolean;
  label_ids?: string[];
  ontvangen?: number;
  search_text?: string;
  snippet?: string;
  subject?: string;
  synced_at?: string;
  thread_id?: string;
  to_addr?: string;
  user_id?: string;
}
