/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelNote {
  aangemaakt?: string;
  deadline?: string;
  gewijzigd?: string;
  id?: string;
  inhoud?: string;
  is_archived?: boolean;
  is_pinned?: boolean;
  kleur?: string;
  linked_event_id?: string;
  prioriteit?: string;
  symbol?: string;
  tags?: string[];
  titel?: string;
  triage_flag?: boolean;
  user_id?: string;
}
