/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelDeviceResponseCurrentState } from './modelDeviceResponseCurrentState';

export interface ModelDeviceResponse {
  commissioned_at?: string;
  current_state?: ModelDeviceResponseCurrentState;
  device_type?: string;
  id?: string;
  ip_address?: string;
  last_seen?: string;
  mac_address?: string;
  manufacturer?: string;
  model?: string;
  name?: string;
  room_id?: string;
  status?: string;
}
