/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelLCProjectCreate {
  deadline?: string;
  fase?: string;
  naam?: string;
  samenvatting?: string;
  start_datum?: string;
  status?: string;
  waarde_indicatie?: number;
}
