/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelLCDecision {
  besluit?: string;
  created_at?: string;
  datum?: string;
  id?: string;
  impact?: string;
  project_id?: string;
  reden?: string;
  status?: string;
  titel?: string;
  user_id?: string;
}
