/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelAutomationRowActionConfig } from './modelAutomationRowActionConfig';
import type { ModelAutomationRowTriggerConfig } from './modelAutomationRowTriggerConfig';

export interface ModelAutomationRow {
  action_config?: ModelAutomationRowActionConfig;
  created_at?: string;
  enabled?: boolean;
  group_name?: string;
  id?: string;
  last_fired_at?: string;
  name?: string;
  trigger_config?: ModelAutomationRowTriggerConfig;
  user_id?: string;
}
