/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */

export interface ModelNoteRevision {
  aangemaakt?: string;
  business_context_id?: string;
  business_context_title?: string;
  business_context_type?: string;
  deadline?: string;
  id?: string;
  inhoud?: string;
  kleur?: string;
  linked_event_id?: string;
  note_id?: string;
  prioriteit?: string;
  symbol?: string;
  tags?: string[];
  titel?: string;
  user_id?: string;
}
