/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Jeffries Homeapp API
 * Backend REST API for Jeffries Homeapp.
 * OpenAPI spec version: 1.0
 */
import type { ModelSceneActionCreate } from './modelSceneActionCreate';

export interface ModelSceneCreate {
  actions?: ModelSceneActionCreate[];
  color_hex?: string;
  icon?: string;
  name?: string;
}
